CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220825150349_initial') THEN
    CREATE TABLE colegio (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        CONSTRAINT "PK_colegio" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220825150349_initial') THEN
    CREATE TABLE curso (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        colegioid integer NOT NULL,
        CONSTRAINT "PK_curso" PRIMARY KEY (id),
        CONSTRAINT "FK_curso_colegio_colegioid" FOREIGN KEY (colegioid) REFERENCES colegio (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220825150349_initial') THEN
    CREATE TABLE asignatura (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name text NOT NULL,
        cursoid integer NOT NULL,
        CONSTRAINT "PK_asignatura" PRIMARY KEY (id),
        CONSTRAINT "FK_asignatura_curso_cursoid" FOREIGN KEY (cursoid) REFERENCES curso (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220825150349_initial') THEN
    CREATE INDEX "IX_asignatura_cursoid" ON asignatura (cursoid);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220825150349_initial') THEN
    CREATE INDEX "IX_curso_colegioid" ON curso (colegioid);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220825150349_initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20220825150349_initial', '6.0.8');
    END IF;
END $EF$;
COMMIT;

